name: Daily Commit

on:
  workflow_dispatch: # allows manual run
  schedule:
    - cron: '30 5 * * *' # runs every day at 11:00 AM IST

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # REQUIRED to push code!

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make a dummy change by 22f3001454@ds.study.iitm.ac.in
        run: |
          echo "Commit at $(date)" >> daily.txt
          git config user.name "Daily Commit Bot"
          git config user.email "22f3001454@ds.study.iitm.ac.in"
          git add daily.txt
          git commit -m "Daily commit on $(date)" || echo "Nothing to commit"

      - name: Push changes
        run: git push
